# Copyright 2022-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "edge-maintenance-agent.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.basicAuthUsername }}
  password: {{ .Values.basicAuthPassword }}
{{- end }}
