{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-maintenance-agent
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      {{- include "edge-maintenance-agent.selectorLabels" . | nindent 6 }}
{{- end }}
