{{/*
# Copyright 2018-present Open Networking Foundation
# Copyright 2018 Intel Corporation

# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
*/}}

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: s1u-net
{{- if $.Values.config.sriov.enabled }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_vfio_s1u_net
{{- end }}
spec:
  config: '{
    "type": {{ .Values.networks.cniPlugin | quote }},
    "ipam": {
        "type": {{ .Values.networks.ipam | quote }}
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sgi-net
{{- if $.Values.config.sriov.enabled }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_vfio_sgi_net
{{- end }}
spec:
  config: '{
    "type": {{ .Values.networks.cniPlugin | quote }},
    "ipam": {
        "type": {{ .Values.networks.ipam | quote }}
    }
  }'
