# Copyright 2021-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

image:
  repository: registry.aetherproject.org/tost/dbuf
  pullPolicy: IfNotPresent
  tag: "latest"
  credentials: {}
  # If specified, use this credential to access the image
  #   registry:
  #   username:
  #   password:

extraParams:
  - '"-max_queues=1024"'


replicaCount: 1
sriovNICSize: 1
sriovResourceName: intel_sriov_netdevice

# Change both in the same time
multusNetworkName: dbuf-sriov
podAnnotations:
    k8s.v1.cni.cncf.io/networks: dbuf-sriov

imagePullSecrets: []
podSecurityContext: {}
resources:
  requests:
    intel.com/intel_sriov_netdevice: '1'
  limits:
    intel.com/intel_sriov_netdevice: '1'

nodeSelector: {}

tolerations: []

affinity: {}
