# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

images:
  tags:
    omecCni: docker.io/omecproject/omec-cni:1.0.0
    sriovPlugin: docker.io/nfvpe/sriov-device-plugin:v3.1
  pullPolicy: IfNotPresent

config:
  sriov:
    # Provide interface used as a SR-IOV PF
    # If your cluster has multiple nodes with different interface names,
    # simply provide the whole list
    resourceList:
      # Provide PF name with VF range for S1U and SGI interfaces.
      # Note that VF range of S1U must be smaller than SGI's.
      vfio:
        s1uPfNames:
          - eno1#0-3
        sgiPfNames:
          - eno1#4-7
      # Provide PF name with its VFs bounded to PF's driver
      # The driver name must be specified to prevent one interface is
      # registered to both vfio and netdevice resource pools
      # NOTE: netDevice is required to use CDN service
      netDevice:
        pfNames:
          - eno1
        drivers:
          - i40evf
          - ixgbevf
