{{/*
# Copyright 2018-present Open Networking Foundation
# Copyright 2018 Intel Corporation

# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only
*/}}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sriov-config
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "sriov_vfio_s1u_net",
          "selectors": {
              "pfNames": {{ toJson .Values.config.sriov.resourceList.vfio.s1uPfNames }},
              "drivers": ["vfio-pci"]
          }
        },
        {
          "resourceName": "sriov_vfio_sgi_net",
          "selectors": {
              "pfNames": {{ toJson .Values.config.sriov.resourceList.vfio.sgiPfNames }},
              "drivers": ["vfio-pci"]
          }
        }
{{- if hasKey .Values.config.sriov.resourceList "netDevice" }}
        ,
        {
          "resourceName": "sriov_netdevice",
          "selectors": {
              "pfNames": {{ toJson .Values.config.sriov.resourceList.netDevice.pfNames }},
              "drivers": {{ toJson .Values.config.sriov.resourceList.netDevice.drivers }}
          }
        }
{{- end }}
      ]
    }
