{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: tb-redis
spec:
  type: ClusterIP
  selector:
    app: tb-redis
  ports:
    - name: tb-redis-port
      port: {{ .Values.config.redis.port }}