{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

*/ -}}

---
apiVersion: v1
kind: Service
metadata:
  name: tb-database
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.config.postgres.port }}
      name: postgres