# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

# Default values for grafana-aether.
# This is a YAML-formatted file.
# This chart loads Grafana and creates configmaps for the datasources and dashboards.

nameOverride: ""
fullnameOverride: ""

globalDashboard: true
multiSiteDashboard: true

# Specify an enterprise to deploy its dashboard, i.e., "telefonica"
enterpriseDashboard: ""

# URL of Prometheus that collects E2E test results from edge monitoring server
edgeServerDatasourceURL: ""

# List of cluster Prometheus datasources.
clusterDatasources: []
# - cluster: production-edge-onf-menlo
#   prometheusURL: http://10.53.154.24

# Configure Google Cloud Monitoring datasource
googleCloudMonitoring: {}
# clientEmail: grafana@onf-vpn.iam.gserviceaccount.com
# defaultProject: onf-vpn
# key: |
#   -----BEGIN PRIVATE KEY-----
#   ...
#   -----END PRIVATE KEY-----

grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
