# Copyright 2021-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

images:
  tags:
    rosCore: docker.io/ros:melodic
    droneNetListener: docker.io/ros:melodic
  pullPolicy: IfNotPresent

nodeSelector:
  enabled: false
  rosCore:
    label: drone-ros-core
    value: enabled

resources:
  enabled: false

config:
  rosCore:
    debug: false
  droneNetListener:
    port: 58080

networks:
  hostNetwork: true

coredns:
  deploy: true
  serviceType: ClusterIP
  service:
    clusterIP: 10.67.128.12
  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: errors
    - name: health
      configBlock: |-
        lameduck 5s
    - name: ready
    - name: forward
      parameters: . 10.67.128.10
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
  - zones:
      - zone: local
    port: 53
    plugins:
    - name: errors
    - name: health
      configBlock: |-
        lameduck 5s
    - name: ready
    - name: hosts
      configBlock: |-
        192.168.251.4 aah.local
        10.250.255.234 spirit-of-adventure.local