{{/*
# Copyright 2019-present Open Networking Foundation
# Copyright 2019 Intel Corporation

# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: spgwu
  labels:
{{ tuple "spgwu" . | include "omec-data-plane.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "spgwu" . | include "omec-data-plane.metadata_labels" | indent 4 }}
  ports:
  - name: dp-comm
    port: {{ .Values.config.spgwu.dpComm.port }}
{{- if .Values.config.spgwu.multiUpfs }}
    protocol: TCP
{{- else }}
    protocol: UDP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: spgwu-headless
  labels:
{{ tuple "spgwu" . | include "omec-data-plane.metadata_labels" | indent 4 }}
spec:
  clusterIP: None
  selector:
{{ tuple "spgwu" . | include "omec-data-plane.metadata_labels" | indent 4 }}
  ports:
  - name: dp-comm
    port: {{ .Values.config.spgwu.dpComm.port }}
{{- if .Values.config.spgwu.multiUpfs }}
    protocol: TCP
{{- else }}
    protocol: UDP
{{- end }}
{{- if and (not .Values.config.spgwu.multiUpfs) .Values.config.spgwu.dpComm.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: spgwu-external
  labels:
{{ tuple "spgwu" . | include "omec-data-plane.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "spgwu" . | include "omec-data-plane.metadata_labels" | indent 4 }}
  type: NodePort
  ports:
  - name: dp-comm
    port: {{ .Values.config.spgwu.dpComm.port }}
    protocol: UDP
    nodePort: {{ .Values.config.spgwu.dpComm.nodePort.port }}
{{- end }}
