{{/*
# Copyright 2019-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only
*/}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: start-stream
  labels:
{{ tuple "video-archive" . | include "cdn-remote.metadata_labels" | indent 4 }}
data:
  start-stream.sh: |
{{ tuple "bin/_start-stream.sh.tpl" . | include "cdn-remote.template" | indent 4 }}
