# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

apiVersion: v1
description: OMEC user plane based on BESS
name: omec-user-plane
icon: https://guide.opencord.org/logos/cord.svg

version: 0.1.3
