# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

dependencies:
  - name: cassandra
    version: 0.13.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: cassandra.deploy
