# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

---
apiVersion: v1
description: Infosys deepstream application for Aether
name: infosys-deepstream

version: 0.1.0
