{
 "title": "Aether Connected Edge (new metrics)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "# ONF\n### Menlo Park\n##### Staging"
   }
  },
  {
   "title": "Test results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_connect_test_ok{endpoint=\"metrics80\",name=\"ace-menlo\"} - aetheredge_e2e_tests_down{endpoint=\"metrics80\",name=\"ace-menlo\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Connect:"
    },
    {
     "expr": "sum(aetheredge_ping_test_ok{endpoint=\"metrics80\",name=\"ace-menlo\"} - aetheredge_e2e_tests_down{endpoint=\"metrics80\",name=\"ace-menlo\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Ping:"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aetheredge_e2e_tests_ok{endpoint=\"metrics80\",name=\"ace-menlo\"}[$__interval]) * 100\n"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) * (1 - aetheredge_e2e_tests_ok{endpoint=\"metrics80\",name=\"ace-menlo\"})) * 100",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) * 100",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Uptime and downtime over time",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aetheredge_e2e_tests_ok{endpoint=\"metrics80\",name=\"ace-menlo\"} * (1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "-1 * sum((1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) * (1 - aetheredge_e2e_tests_down{endpoint=\"metrics80\",name=\"ace-menlo\"}) * (1 - aetheredge_e2e_tests_ok{endpoint=\"metrics80\",name=\"ace-menlo\"}))",
     "legendFormat": "Down: unscheduled"
    },
    {
     "expr": "-1 * sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "Down: scheduled"
    },
    {
     "expr": "-1 * sum((1 - aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"ace-menlo\"}) * aetheredge_e2e_tests_down{endpoint=\"metrics80\",name=\"ace-menlo\"})",
     "legendFormat": "Test down"
    }
   ]
  },
  { "title": "SD-CORE Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active subscribers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spgw_number_of_ue_attached{cp_mode=\"spgw\",state=\"active\",level=\"subscribers\",job=\"spgwc-metrics\"})",
     "legendFormat": "SPGW"
    },
    {
     "expr": "sum(mme_number_of_ue_attached{endpoint=\"metrics3081\",level=\"subscribers\",sub_state=\"Active\"})",
     "legendFormat": "MME"
    }
   ]
  },
  {
   "title": "SPGW Procedures: Successes Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"success\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    },
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"success\",mme_addr=\"\",proc_type=\"INITIAL_ATTACH\"}[5m])) by (proc_type)",
     "legendFormat": "{{proc_type}}"
    }
   ]
  },
  {
   "title": "SPGW Procedures: Failures Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"failure\",mme_addr=\"\",proc_type=\"\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    },
    {
     "expr": "sum(rate(number_of_procedures{cp_mode=\"spgw\", service=\"spgwc-metrics\",result=\"failure\",mme_addr=\"\",proc_type=\"INITIAL_ATTACH\"}[5m])) by (proc_type)",
     "legendFormat": "{{proc_type}}"
    }
   ]
  },
  {
   "title": "MME Procedures: Successes Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"success\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "MME Procedures: Failures Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_procedures{endpoint=\"metrics3081\",mme_app=\"procedure\",proc_result=\"failure\"}[5m])) by (procedure)",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Ready replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"aether-system\"}",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "HSS Messages Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(number_of_messages_sent{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    },
    {
     "expr": "sum(rate(number_of_messages_received{endpoint=\"metrics3081\",interface=\"s6a\"}[5m])) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    }
   ]
  }
 ]
}