{
 "title": "Aether Connected Edge",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "edge",
    "label": "Edge",
    "query": "aetheredge_status_control_plane"
   }
  ]
 },
 "panels": [
  { "title": "VPN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPN connections from Google Cloud",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{ metric.label.tunnel_name }}",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.tunnel_name",
       "=",
       "production-ace-*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "onf-vpn",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  { "title": "Edge: $edge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "edge" },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"$edge\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"$edge\"}))",
     "legendFormat": "Control Plane"
    },
    {
     "expr": "sum(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"$edge\"} - (10*aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"$edge\"}))",
     "legendFormat": "User Plane"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"$edge\"} - 1, 0) * 100)",
     "legendFormat": "Control Plane"
    },
    {
     "expr": "sum(clamp_min(aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"$edge\"} - 1, 0) * 100)",
     "legendFormat": "User Plane"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(1 - (clamp_min(aetheredge_status_control_plane{endpoint=\"metrics80\",name=\"$edge\"} + aetheredge_status_user_plane{endpoint=\"metrics80\",name=\"$edge\"} - 3, 0) + aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"$edge\"}), 0))",
     "legendFormat": "Unscheduled"
    },
    {
     "expr": "sum(aetheredge_in_maintenance_window{endpoint=\"metrics80\",name=\"$edge\"})",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "title": "Seconds since last update",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(time() - aetheredge_last_update{endpoint=\"metrics80\",name=\"$edge\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Test status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Seconds since last update",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(time() - aetheredge_last_update{endpoint=\"metrics80\",name!~\"production.*|.*dongle|ace-argela\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}