{
 "title": "Kubernetes / Logs / Pod",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "es_datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "es_namespace",
    "label": "Namespace",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.namespace_name.keyword\"}\t"
   },
   {
    "name": "es_pod",
    "label": "Pod",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.pod_name.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$es_namespace\"}\t"
   },
   {
    "name": "es_container",
    "label": "Container",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.container_name.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$es_namespace AND kubernetes.pod_name.keyword:$es_pod\"}\t"
   },
   {
    "name": "es_loglevel",
    "label": "Log Level",
    "query": "{\"find\": \"terms\", \"field\": \"logLevel.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$es_namespace AND kubernetes.pod_name.keyword:$es_pod AND kubernetes.container_name.keyword:$es_container\"}\t"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace $es_namespace: Log Messages Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3957",
       "fake": true,
       "field": "kubernetes.pod_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:195",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:193",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.namespace_name.keyword:$es_namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod $es_pod: Log Messages per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:191",
       "fake": true,
       "field": "kubernetes.container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:195",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:193", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod_name.keyword:$es_pod AND kubernetes.namespace_name.keyword:$es_namespace AND (logLevel.keyword:$es_loglevel)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$es_pod Logs ($es_container)",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:381",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:211",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.container_name.keyword:$es_container AND kubernetes.pod_name.keyword:$es_pod AND kubernetes.namespace_name.keyword:$es_namespace AND (logLevel.keyword:$es_loglevel)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}