{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
*/}}

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: access-net
{{- if $.Values.config.upf.sriov.enabled }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_vfio_access_net
{{- end }}
spec:
  config: '{
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
    "cniVersion": "0.3.1",
{{- end }}
    "type": {{ .Values.config.upf.cniPlugin | quote }},
    "ipam": {
        "type": {{ .Values.config.upf.ipam | quote }}
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: core-net
{{- if $.Values.config.upf.sriov.enabled }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_vfio_core_net
{{- end }}
spec:
  config: '{
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
    "cniVersion": "0.3.1",
{{- end }}
    "type": {{ .Values.config.upf.cniPlugin | quote }},
    "ipam": {
        "type": {{ .Values.config.upf.ipam | quote }}
    }
  }'
