{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

*/ -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: phylo
  labels:
{{ tuple "phylo" . | include "phylo.metadata_labels" | indent 4 }}
data:
  run-video-analytics-server.sh: |
{{ tuple "bin/_run-video-analytics-server.sh.tpl" . | include "phylo.template" | indent 4 }}
