{{- /*

# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

*/ -}}

---
apiVersion: v1
kind: Service
metadata:
  name: wowza
  labels:
{{ tuple "wowza" . | include "phylo.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "wowza" . | include "phylo.metadata_labels" | indent 4 }}
  ports:
    - port: 554 #
      targetPort: 554
      protocol: TCP
      name: tcp-554
    - port: 1935 # RTMP/RTMPT/RTMPE/RTSP(interleaved)
      targetPort: 1935
      protocol: TCP
      name: tcp-1935
    - port: 8084 #
      targetPort: 8084
      protocol: TCP
      name: tcp-8084
    - port: 8085 #
      targetPort: 8085
      protocol: TCP
      name: tcp-8085
    - port: 8086 #
      targetPort: 8086
      protocol: TCP
      name: tcp-8086
    - port: 8087 #
      targetPort: 8087
      protocol: TCP
      name: tcp-8087
    - port: 8088 #
      targetPort: 8088
      protocol: TCP
      name: tcp-8088
---
apiVersion: v1
kind: Service
metadata:
  name: wowza-external
  labels:
{{ tuple "wowza" . | include "phylo.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "wowza" . | include "phylo.metadata_labels" | indent 4 }}
  type: NodePort
  ports:
    - name: management
      port: 8088
      protocol: TCP
      nodePort: 30088
    - name: rtmp
      port: 1935 # RTMP/RTMPT/RTMPE/RTSP(interleaved)
      targetPort: 1935
      protocol: TCP
      nodePort: 31935
