# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only

dependencies:
- name: base-kubernetes
  version: 1.2.1
  repository: https://charts.opencord.org
- name: mcord-services
  version: 1.1.8
  repository: https://charts.opencord.org
  condition: mcord-services.enabled
- name: seba-services
  version: 1.2.8
  repository: https://charts.opencord.org
  condition: seba-services.enabled
- name: onos
  version: 1.1.3
  repository: https://charts.opencord.org
  condition: mcord-services.progran.enabled
  alias: onos-progran
